sudo: required

services:
  - docker

language: python
python:
  - "3.6"

git:
  quiet: true
  depth: 1

before_install:
  - docker pull alpine:3.8

install:
  - pip install pexpect
  - docker run --env "DOCKER_SHELL=sh_on_alpine" --interactive --detach --name sh_on_alpine alpine:3.8

before_script:
  - docker ps

script:
  - tests/sh.py

notifications:
  email:
    - alu@byteberry.net
