sudo: required

services:
  - docker

language: python
python:
  - "3.6"

git:
  quiet: true
  depth: 1

before_install:
  - docker pull alpine:3.8
  - docker pull ubuntu:18.04
  - docker pull zshusers/zsh-5.6.2
  - docker pull frapsoft/fish

install:
  - pip install pexpect
  - docker run --env "DOCKER_SHELL=sh_on_alpine" --interactive --detach --name shell_sh_on_alpine alpine:3.8
  - docker run --env "DOCKER_SHELL=bash_on_ubuntu" --interactive --detach --name shell_bash_on_ubuntu ubuntu:18.04
  - docker run --env "DOCKER_SHELL=zsh_on_jessie" --interactive --detach --name shell_zsh_on_jessie zshusers/zsh-5.6.2
  - docker run --env "DOCKER_SHELL=fish_on_alpine" --interactive --detach --name shell_fish_on_alpine frapsoft/fish fish

before_script:
  - docker ps

script:
  - tests/sh.py
  - tests/bash.py
  - tests/zsh.py
  - tests/fish.py

notifications:
  email:
    - alu@byteberry.net
